.TH FIFOREAD 8 "4 April 2003"
.SH NAME
fiforead \- test program for aprsdigi.
.SH SYNOPSIS
.nf
.BI "fiforead " filename
.fi
.SH DESCRIPTION
.PP
.I Fiforead
is useful for testing aprsdigi.  Unix datagrams received from 
.BI "aprsdigi \-p:unix:" filename,callsign,alias...
are written to stdout.
.SH AUTHOR
.nf
Alan Crosswell, n2ygk@weca.org
.fi
